//! The scene's asset table: the bridge between the opaque resource handles
//! stored on components ([`MeshHandle`]/[`TextureHandle`]/[`MaterialHandle`])
//! and the *stable* descriptions that survive a save/load round-trip — a mesh's
//! file path or builtin name, a texture's file path, and a material's PBR
//! parameters.
//!
//! [`SceneAssets`] is the single authority for these handles: registering a
//! source returns a handle, and re-registering the *same* source returns the
//! same handle (so loading the same file path twice is free). The renderer's
//! `ResourceCache` is then populated at exactly these handles by the app, which
//! is the layer that owns the GPU.

use std::collections::HashMap;
use std::path::PathBuf;

use elderforge_core::handles::{MaterialHandle, MeshHandle, TextureHandle};
use elderforge_core::math::Vec4;
use serde::{Deserialize, Serialize};

/// Where a mesh's geometry comes from.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum MeshSource {
    /// A primitive generated by the renderer at runtime (`"cube"`, `"sphere"`,
    /// `"capsule"`, `"plane"`). Not backed by a file.
    Builtin(String),
    /// A mesh file on disk (`.obj` / `.gltf` / `.glb`).
    File(PathBuf),
}

/// Where a texture's pixels come from.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum TextureSource {
    /// An image file on disk (PNG / JPEG).
    File(PathBuf),
}

/// Serializable PBR material parameters — the renderer's `PbrMaterial` without
/// the GPU coupling. Texture maps are referenced by [`TextureHandle`] into the
/// same [`SceneAssets`] table.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MaterialDef {
    pub albedo: Vec4,
    pub roughness: f32,
    pub metallic: f32,
    pub albedo_map: Option<TextureHandle>,
    pub normal_map: Option<TextureHandle>,
}

impl Default for MaterialDef {
    fn default() -> Self {
        Self {
            albedo: Vec4::ONE,
            roughness: 0.5,
            metallic: 0.0,
            albedo_map: None,
            normal_map: None,
        }
    }
}

/// Resource handles → stable descriptions for one scene. Handles are assigned
/// densely from index 0 with generation 0; the position in each list *is* the
/// handle index, which keeps serialization compact (handles are implicit in
/// list order) and reload deterministic.
#[derive(Debug, Clone, Default)]
pub struct SceneAssets {
    meshes: Vec<MeshSource>,
    textures: Vec<TextureSource>,
    materials: Vec<MaterialDef>,
    mesh_lookup: HashMap<MeshSource, MeshHandle>,
    texture_lookup: HashMap<TextureSource, TextureHandle>,
}

impl SceneAssets {
    pub fn new() -> Self {
        Self::default()
    }

    /// Register a mesh source, returning its handle. Registering a source that
    /// is already present returns the existing handle (so the same file or
    /// builtin is never uploaded twice).
    pub fn register_mesh(&mut self, source: MeshSource) -> MeshHandle {
        if let Some(handle) = self.mesh_lookup.get(&source) {
            return *handle;
        }
        let handle = MeshHandle::new(self.meshes.len() as u32, 0);
        self.meshes.push(source.clone());
        self.mesh_lookup.insert(source, handle);
        handle
    }

    /// Register a texture source, returning its handle (deduped by source).
    pub fn register_texture(&mut self, source: TextureSource) -> TextureHandle {
        if let Some(handle) = self.texture_lookup.get(&source) {
            return *handle;
        }
        let handle = TextureHandle::new(self.textures.len() as u32, 0);
        self.textures.push(source.clone());
        self.texture_lookup.insert(source, handle);
        handle
    }

    /// Register a material, returning its handle. Materials are not deduplicated
    /// (two visually identical materials stay distinct handles).
    pub fn register_material(&mut self, material: MaterialDef) -> MaterialHandle {
        let handle = MaterialHandle::new(self.materials.len() as u32, 0);
        self.materials.push(material);
        handle
    }

    /// The source for a mesh handle, if it belongs to this table.
    pub fn mesh_source(&self, handle: MeshHandle) -> Option<&MeshSource> {
        self.meshes.get(handle.index() as usize)
    }

    /// The source for a texture handle, if it belongs to this table.
    pub fn texture_source(&self, handle: TextureHandle) -> Option<&TextureSource> {
        self.textures.get(handle.index() as usize)
    }

    /// The parameters for a material handle, if it belongs to this table.
    pub fn material(&self, handle: MaterialHandle) -> Option<&MaterialDef> {
        self.materials.get(handle.index() as usize)
    }

    /// Every mesh handle and its source, in handle-index order.
    pub fn meshes(&self) -> impl Iterator<Item = (MeshHandle, &MeshSource)> {
        self.meshes
            .iter()
            .enumerate()
            .map(|(i, source)| (MeshHandle::new(i as u32, 0), source))
    }

    /// Every texture handle and its source, in handle-index order.
    pub fn textures(&self) -> impl Iterator<Item = (TextureHandle, &TextureSource)> {
        self.textures
            .iter()
            .enumerate()
            .map(|(i, source)| (TextureHandle::new(i as u32, 0), source))
    }

    /// Every material handle and its parameters, in handle-index order.
    pub fn materials(&self) -> impl Iterator<Item = (MaterialHandle, &MaterialDef)> {
        self.materials
            .iter()
            .enumerate()
            .map(|(i, def)| (MaterialHandle::new(i as u32, 0), def))
    }

    /// Rebuild a table from ordered source/material lists (used by the loader).
    /// The list position becomes the handle index, matching what serialization
    /// wrote.
    pub fn from_parts(
        meshes: Vec<MeshSource>,
        textures: Vec<TextureSource>,
        materials: Vec<MaterialDef>,
    ) -> Self {
        let mut assets = Self::default();
        for source in meshes {
            assets.register_mesh(source);
        }
        for source in textures {
            assets.register_texture(source);
        }
        assets.materials = materials;
        assets
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn registering_dedups_meshes_by_source() {
        let mut assets = SceneAssets::new();
        let a = assets.register_mesh(MeshSource::Builtin("cube".into()));
        let b = assets.register_mesh(MeshSource::Builtin("cube".into()));
        let c = assets.register_mesh(MeshSource::File("models/x.obj".into()));
        assert_eq!(a, b, "same source -> same handle");
        assert_ne!(a, c);
        assert_eq!(assets.mesh_source(a), Some(&MeshSource::Builtin("cube".into())));
    }

    #[test]
    fn materials_are_distinct_per_registration() {
        let mut assets = SceneAssets::new();
        let a = assets.register_material(MaterialDef::default());
        let b = assets.register_material(MaterialDef::default());
        assert_ne!(a, b);
        assert_eq!(assets.materials().count(), 2);
    }

    #[test]
    fn from_parts_preserves_handle_indices() {
        let sources = vec![
            MeshSource::Builtin("cube".into()),
            MeshSource::File("a.obj".into()),
        ];
        let assets = SceneAssets::from_parts(sources, vec![], vec![]);
        assert_eq!(
            assets.mesh_source(MeshHandle::new(1, 0)),
            Some(&MeshSource::File("a.obj".into()))
        );
    }
}
